spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb:http://CLIENT-SERVICE
          predicates:
            - Path=/api/clients/**, /client-service/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/devices/**, /api/units/**, /api/games/**, /product-service/**
        - id: rental-service
          uri: lb:http://RENTAL-SERVICE
          predicates:
            - Path=/api/rentals/**, /rental-service/**
server:
  port: 8222
