spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8070

application:
  config:
    client-url: http://localhost:8222/api
    product-url: http://localhost:8222/api