apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: vladdima21/config-server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8888
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 9411
          #   initialDelaySeconds: 25
          #   periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
