apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: vladdima21/product-service:latest
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8050
            initialDelaySeconds: 25
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8050
            initialDelaySeconds: 40
            periodSeconds: 5
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: [ 'sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 2; done;' ]
        - name: wait-for-postgres-product
          image: busybox
          command: [ 'sh', '-c', 'until nc -z postgres-product 5432; do echo waiting for postgres-product; sleep 2; done;' ]
        - name: wait-for-zipkin
          image: busybox
          command: [ 'sh', '-c', 'until nc -z zipkin 9411; do echo waiting for zipkin; sleep 2; done;' ]
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  ports:
    - port: 8050
      targetPort: 8050
  selector:
    app: product-service
